### PR TITLE
App icons for Sandstorm package

### LINKED ISSUE #41: App Icons for Sandstorm Package
Hi @mitar! I'm happy to help out with designing an a set of icons for your app. Since you haven't yet decided on a name, maybe it would help for you to list about 10 words that describe your app/logo to help me come up with some concepts. [Here are some words that phildini chose for ContactOtter.](https://github.com/phildini/logtacts/issues/17#issuecomment-172638915)

If you already have a concept in mind, that's great too. :)

### PR DESCRIPTION
**Pull request by neynah**
These are all SVGs so you can edit them. Fixes #41.

### CODE REVIEW

**Comment by neynah** [comment]
@mitar Regarding the copyright:

These images are created by me and the copyright for them is owned by Sandstorm Development Group, Inc. We are OK with this license being used to redistribute & modify the works: https://creativecommons.org/licenses/by-sa/4.0 For the purposes of CC license attribution, I'm happy for people re-using the work to credit them to the Peer Mind project. If, down the road, you need any other permissions or licensing from us, we're happy to oblige.

**Comment by mitar** [comment]
OK, I do not want to sound ungrateful now, but maybe my lawyer friends brainwashed me too much. But now that I am thinking more, I do not think CC license will work for the logo. Because just imagine that some news outlet would like to use our logo in an article about us, they would have to attribute and this could blow up their lawyers. And if they would request a different permission to use it, then we would have to contact Sandstorm, which would make it all complicated.

From me looking at other open source projects, it seems they all tend to be strict about trademarking their name and logo, while keeping the rest of the content open. In some way, the name is what they control, while the content is free.

So I think what I would need from you is to grant me (that is, the project) some sort of a non-exclusionary license to do literally anything with the logo. So then Sandstorm can do anything (display it in the app, use it for promotion), you can do (show it elsewhere), but also the project can do as needed in the future anything. In practice we will of course use logo in connection with the project, so attribution to the project will be more or less clear. And your contribution will be seen through this pull request and in general through contributors to the project through repository. This, that both Sandstorm and you can do anything with logo as well is generally tricky for the project, but I do believe you will not use it in strange ways which would inflict on the project's good name.

I can come up with some text to this effect if this would be OK.

**Comment by neynah** [comment]
Hi @mitar , that sounds fine with us. One standard set of boilerplate for that is the Apache Software Foundation CLA: http://oss-watch.ac.uk/resources/cla some further information on it. We use something like that at Sandstorm. What you want seems similar to the discussion of "license lock" at https://julien.ponge.org/blog/in-defense-of-contributor-license-agreements . Let me know once you have something written-down that I can review (and almost definitely agree to). Feel free to merge this as-is, or wait for a different license grant etc.

**Comment by mitar** [comment]
OK, back in action. I have added a [CLA bot](http://clahub.com/) to the repository and used [Harmony CLA agreement template](http://harmonyagreements.org/). Please sign it through the service and then I will merge it.

Thanks again.

**Comment by neynah** [comment]
Done!

**Comment by mitar** [comment]
Perfect! Thanks.

**Comment by mitar** [comment]
Hm, Inkspace and Gimp have issues opening them. They do not render them correctly. :-(

**Comment by neynah** [comment]
:( Screenshots? I'm happy to re-export.

**Comment by mitar** [comment]
screen shot 2016-08-08 at 10 18 40 am
screen shot 2016-08-08 at 10 18 02 am

What tool are you using? Is there a way to export it into SVG with some older version of SVG standard or something? It seems this SVG is too fancy. It does open in browsers though. I have not seen a browser with issues. Only image manipulation tools. (I wanted to create favicons.)

**Pull request merged**
