### PR TITLE
feature(motion): fix ui-glitch in voting slider

### PR DESCRIPTION
**Pull request by chilldude**

### CODE REVIEW

**Comment by chilldude** [comment]
@mitar weird thing is happening with the jquery selectors working with ReactiveFields

**Comment by mitar** [comment]
OK, let me do one pass over this and remove previous slider and use the new one, OK?

**Comment by mitar** [comment]
I think it works now.

**Comment by mitar** [comment]
Try resizing the window. Slider does not resize correctly.

**Comment by chilldude** [comment]
Cool, this looks correct

**Comment by mitar** [comment]
@chilldude: Any progress on this?

**Comment by mitar** [comment]
See the https://github.com/peer/mind/issues/67 ticket for ideas for UI improvements here.

**Comment by mitar** [comment]
Failing tests are normal currently. Do not worry about that.

**Comment by mitar** [comment]
Looks good. Merging.

I also fixed test.

**Comment by chilldude** [comment]
👍

**Pull request merged**
