### PR TITLE
V2 set of svg icons

### PR DESCRIPTION
**Pull request by neynah**
Let's try again! :)

### CODE REVIEW

**Comment by mitar** [comment]
SVG 1.0 format please. :-)

**Comment by mitar** [comment]
And thanks. This is much better. There is just a slight gap on the blue top edge, but otherwise looks good.

**Comment by neynah** [comment]
Hmm. Illustrator is funny in that when I use the export option instead of save as SVG it doesn't seem to let me choose the SVG version. I will attempt again.

**Comment by neynah** [comment]
Okay so I can't export SVG 1.0. However, what I can do is provide 2 sets of icons. 1 set will be SVG 1.0 so that you can edit it, the other will be whatever export > SVG produces (this PR) so that it will display nicely in web.

**Comment by mitar** [comment]
Thanks! I think I managed to do everything with them. I had to manually edit files a bit in the text editor. :-)

**Pull request merged**
